version: "3.7"
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    networks:
      - chickinnetwork
    volumes: 
      - cache:/data
  smartfarm-stg:
    build: .
    # image: ${APP_IMAGE_STG}:${APP_IMAGE_STG_TAG}
    container_name: smartfarm-staging
    environment:
      SERVER_PORT: 3102
      NODE_ENV: staging
      MONGO_CONNECTIONSTRING: mongodb+srv://chickindb:IniDBch1ck1n@cluster0.i3lie19.mongodb.net?retryWrites=true&w=majority
      DB_NAME: chckin-stagging
      DB_NAME_AUTH: chickin-auth-stagging
      AUTH_URL: https://staging-auth.chickinindonesia.com
      BE_URL: https://staging-smartfarm.chickinindonesia.com
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      REDIS_TIME: 300
    volumes:
      - ./uploads:/app/uploads
      - cache:/data
    networks:
      - chickinnetwork
    ports:
      - "3102:3102"
    restart: always
networks:
  chickinnetwork:
    external: true
volumes:
  cache:
    name: chickin-be_cache
    external: true



