version: '3.7'
services:
  smartfarm-stg:
    build: .
    # image: ${APP_IMAGE_STG}:${APP_IMAGE_STG_TAG}
    container_name: smartfarm-staging
    environment:
      SERVER_PORT: 3102
      NODE_ENV: staging
      DB_HOST: chickinstaging.ccjbqbp7dpx4.ap-southeast-1.docdb.amazonaws.com
      DB_PORT: 27017
      DB_USER: chickindb
      DB_PASS: IniDBch1ck1n
      DB_NAME: chckin-stagging
      DB_NAME_AUTH: chickin-auth-stagging
      AUTH_URL: https://staging-auth.chickinindonesia.com
    volumes:
      - /sites/apps/smartfarm/uploads:/app/uploads
    networks:
      - chickinnetwork
    ports:
      - "3102:3102"
    restart: always
networks:
  chickinnetwork:
    external: true
