version: "3.7"
services:
  smartfarm-stg:
    image: ${APP_IMAGE_STG}:${APP_IMAGE_STG_TAG}
    container_name: smartfarm-staging
    environment:
      SERVER_PORT: 3102
      NODE_ENV: staging
      MONGO_CONNECTIONSTRING: $MONGO_CONNECTIONSTRING_STG
      DB_NAME: chckin-stagging
      DB_NAME_AUTH: chickin-auth-stagging
      AUTH_URL: https://staging-auth.chickinindonesia.com
      BE_URL: https://staging-smartfarm.chickinindonesia.com
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      REDIS_TIME: 300
    volumes:
      - /sites/apps/smartfarm/uploads:/app/uploads
      - cache:/data
    networks:
      - chickinnetwork
    ports:
      - "3102:3102"
    restart: always
networks:
  chickinnetwork:
    external: true
volumes:
  cache:
    name: cache-compose_cache
    external: true



