version: "3.9"
services:
  smartfarm-prod:
    image: ${APP_IMAGE_PROD}:${APP_IMAGE_PROD_TAG}
    container_name: smartfarm-production
    environment:
      SERVER_PORT: 3101
      NODE_ENV: production
      MONGO_CONNECTIONSTRING: 
      DB_NAME: chckin
      DB_NAME_AUTH: chickin-auth
      AUTH_URL:
      BE_URL: 
      IOT_URL: iot-production:3103
      REDIS_PATH : 0
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
      REDIS_TIME: 300
      BE_API_KEY:
    volumes:
      - /home/chickin/projects/smartfarm/upload-prod:/app/uploads
      - cache:/data
    networks:
      - chickinnetwork
    ports:
      - "3101:3101"
    restart: always
networks:
  chickinnetwork:
    external: true
volumes:
  cache:
    name: cache-compose_cache
    external: true
