version: "3.9"
services:
  smartfarm-prod:
    build: .
    # image: ${APP_IMAGE_PROD}:${APP_IMAGE_PROD_TAG}
    container_name: smartfarm-production
    environment:
      SERVER_PORT: 3101
      MONGO_CONNECTIONSTRING: mongodb+srv://chickinProdDBUser:M4ziLdjSHLTuaqLq@chickinprodcluster.mgumb9a.mongodb.net/?retryWrites=true&w=majority
      DB_NAME: chckin
      DB_NAME_AUTH: chickin-auth
      AUTH_URL: https://auth.chickinindonesia.com
      BE_URL: https://smartfarm.chickinindonesia.com
    volumes:
      - /sites/apps/smartfarm/uploads:/app/uploads
    networks:
      - chickinnetwork
    ports:
      - "3101:3101"
    restart: always
networks:
  chickinnetwork:
    external: true