version: "3.9"
services:
  smartfarm-prod:
    image: ${APP_IMAGE_PROD}:${APP_IMAGE_PROD_TAG}
    container_name: smartfarm-production
    environment:
      SERVER_PORT: 3101
      NODE_ENV: production
      DB_HOST: $DB_HOST_PROD
      DB_PORT: 27017
      DB_USER: $DB_USER_PROD
      DB_PASS: $DB_PASS_PROD
      DB_NAME: chckin
      DB_NAME_AUTH: chickin-auth
      AUTH_URL: https://auth.chickinindonesia.com
    volumes:
      - /sites/apps/smartfarm/uploads:/app/uploads
    networks:
      - chickinnetwork
    ports:
      - "3101:3101"
    restart: always
networks:
  chickinnetwork:
    external: true